apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhi-operator-index-dev
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/rh_integration/rhi-operator-index-dev:0.0.7
